export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const UPDATE_INGREDIENTS = 'UPDATE_INGREDIENTS';
export const FETCHED_INGREDIENTS_SUCCESS = 'FETCHED_INGREDIENTS_SUCCESS';
export const FETCHED_INGREDIENTS_FAIL = 'FETCHED_INGREDIENTS_FAILED';

export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS';
export const PURCHASE_BURGER_FAIL = 'PURCHASE_BURGER_FAILED';

export const FETCHED_ORDERS_SUCCESS = 'FETCHED_INGREDIENTS_SUCCESS';
export const FETCHED_ORDERS_FAIL = 'FETCHED_INGREDIENTS_FAILED';

export const DELETE_ORDER_SUCCESS = 'DELETE_ORDER_SUCCESS';
export const DELETE_ORDER_FAIL = 'DELETE_ORDER_FAIL';

export const AUTHENTICATE_USER_SUCCESS = 'AUTHENTICATE_USER_SUCCESS';
export const AUTHENTICATE_USER_FAIL = 'AUTHENTICATE_USER_FAIL';

export const LOGOUT_AUTH_USER = 'LOGOUT_AUTH_USER';

export const DELETE_ALL_ORDERS = 'DELETE_ALL_ORDERS';

export const IS_LOGGED_IN_WITH_BUILT_BURGER = 'IS_LOGGED_IN_WITH_BUILT_BURGER';
